config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :groups, only: [:index, :show], param: :token do
        resources :shows, only: [:index, :show], param: :name do
          patch 'episodes', to: 'episodes#update'
          patch 'staff', to: 'staff#update'
        end
      end
    end
  end

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  resources :groups do
    resources :shows do
      resources :episodes do
        resources :staff, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :terms, only: [:new, :create, :destroy]
      resources :projects, only: [:new, :create, :update, :destroy]
    end

    resources :tokens, only: [:update]
    resources :members, except: [:show]
    resources :users, except: [:edit, :update]
    resources :webhooks, except: [:show]
    resources :positions, except: [:show]
    resources :projects, only: [:index]
  end

  get 'donations', to: 'donations#index'
  get 'documentation', to: 'documentation#index'
  get 'documentation/discord', to: 'documentation#discord'
  get 'documentation/api', to: 'documentation#api'
  get 'documentation/webhooks', to: 'documentation#webhooks'
end

app/models/position.rb
# == Schema Information
#
# Table name: positions
#
#  id         :bigint           not null, primary key
#  acronym    :string           not null
#  name       :string           not null
#  rank       :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :bigint           not null
#
# Indexes
#
#  index_positions_on_acronym   (acronym)
#  index_positions_on_group_id  (group_id)
#  index_positions_on_name      (name)
#
# Foreign Keys
#
#  fk_rails_...  (group_id => groups.id)
#
class Position < ApplicationRecord
  has_many :staff, dependent: :destroy
  belongs_to :group, touch: true

  acts_as_list scope: :group, column: :rank

  validates :name, presence: true,
                   uniqueness: {
                     scope: :group,
                     message: "Position Names must be unique."
                   }

  validates :acronym, presence: true,
                      format: { with: /\A[a-zA-Z0-9]+\Z/ },
                      uniqueness: {
                        scope: :group,
                        message: "Position Acronyms must be unique."
                      }

  def self.where_name_or_acronym_equals!(value)
    positions = where(
      'lower(name) = ? OR lower(acronym) = ?',
      value.downcase,
      value.downcase
    )

    raise PositionNotFoundError if positions.size == 0
    return positions
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action do
    authenticate_user!
    set_group
    authenticate_group!

    add_breadcrumb "Groups", groups_url
    add_breadcrumb @group.name, group_url(@group)
  end

  def index
  end

  def new
    @position = Position.new
  end

  def edit
    add_breadcrumb "Positions", group_positions_url(@group)
    @position = @group.positions.find(params[:id])
  end

  def create
    @position = Position.new(position_params)
    @position.group = @group

    if @position.save
      redirect_to group_positions_url(@group)
    else
      render 'new'
    end
  end

  def update
    @position = @group.positions.find(params[:id])

    if @position.update(position_params)
      redirect_to group_positions_url(@group), notice: "Updated #{@position.name}"
    else
      render 'edit'
    end
  end

  def destroy
    @position = @group.positions.find(params[:id])

    if @position.destroy
      redirect_to group_positions_url(@group), notice: "Deleted #{@position.name}"
    else
      render 'edit'
    end
  end

  private
    def position_params
      params.require(:position).permit(:name, :acronym, :rank)
    end
end

app/views/positions/_form.html.erb
<%= form_with model: [@group, @position], local: true do |f| %>
  <h3 class="text-lg leading-6 font-medium text-gray-900">
    Information
  </h3>
  <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
    Positions track the different roles members will be assigned while working on a Show.
  </p>

  <%= render partial: "layouts/errors", locals: { record: @position } %>

  <div class="mt-12">
    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :name, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.text_field :name, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :acronym, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <%# <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs"> %>
        <div class="max-w-lg sm:max-w-xs">
          <%= render partial: 'forms/text_input', locals: { f: f, record: @position, key: :acronym } %>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-8 border-t border-gray-200 pt-5">
    <div class="flex justify-end">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to "Cancel", group_positions_url(@group), class: "py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <%= f.submit @position.new_record? ? "Create Position" : "Edit Position", class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out" %>
      </span>
    </div>
  </div>
<% end %>

app/views/positions/_position.html.erb
<tr class="bg-white" data-sortable-update-url="<%= group_position_url(@group, position) %>">
  <td>
    <svg class="handle w-4 h-4 mr-auto ml-auto cursor-move" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M3 7a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 13a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
   </svg>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
    <%= position.name %>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
    <%= position.acronym %>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
    <%= link_to "Edit", edit_group_position_url(@group, position), class: "text-indigo-600 hover:text-indigo-900" %>
  </td>
  <td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
    <%= link_to "Delete", group_position_url(@group, position), method: :delete, data: { confirm: "Do you wish to delete #{position.name}? This will also delete all staff positions associated with it!" }, class: "text-red-600 hover:text-red-900" %>
  </td>
</tr>

app/views/positions/edit.html.erb
<% content_for :title, 'Edit Position' %>

<%= render partial: 'positions/form' %>

app/views/positions/index.html.erb
<% content_for :title, 'Positions' %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Add Position', url: new_group_position_url(@group), highlight: true }]}  %>
<% end %>

<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <% if @group.positions.empty? %>
        <%= render partial: 'layouts/empty', locals: { content: "Your group does not have any positions!" } %>
      <% else %>
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
          <table class="min-w-full divide-y divide-gray-200">
            <thead>
              <tr>
                <th class="px-3 py-3 bg-gray-50"></th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Name
                </th>
                <th class="px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                  Acronym
                </th>
                <th class="px-6 py-3 bg-gray-50"></th>
                <th class="px-6 py-3 bg-gray-50"></th>
              </tr>
            </thead>
            <tbody data-controller="sortable" data-sortable-resource-value="position" data-sortable-parameter-value="rank">
              <%= render partial: 'positions/position', collection: @group.positions, cached: true %>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/positions/new.html.erb
<% content_for :title, 'Create New Position' %>

<%= render partial: 'positions/form' %>

app/views/positions/show.html.erb
<h1>Positions#show</h1>
<p>Find me in app/views/positions/show.html.erb</p>