config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :groups, only: [:index, :show], param: :token do
        resources :shows, only: [:index, :show], param: :name do
          patch 'episodes', to: 'episodes#update'
          patch 'staff', to: 'staff#update'
        end
      end
    end
  end

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  resources :groups do
    resources :shows do
      resources :episodes do
        resources :staff, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :terms, only: [:new, :create, :destroy]
      resources :projects, only: [:new, :create, :update, :destroy]
    end

    resources :tokens, only: [:update]
    resources :members, except: [:show]
    resources :users, except: [:edit, :update]
    resources :webhooks, except: [:show]
    resources :positions, except: [:show]
    resources :projects, only: [:index]
  end

  get 'donations', to: 'donations#index'
  get 'documentation', to: 'documentation#index'
  get 'documentation/discord', to: 'documentation#discord'
  get 'documentation/api', to: 'documentation#api'
  get 'documentation/webhooks', to: 'documentation#webhooks'
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :bigint           not null, primary key
#  acronym    :string           not null
#  name       :string           not null
#  slug       :string
#  token      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_groups_on_acronym  (acronym) UNIQUE
#  index_groups_on_name     (name) UNIQUE
#  index_groups_on_slug     (slug) UNIQUE
#  index_groups_on_token    (token) UNIQUE
#
require 'net/http'

class Group < ApplicationRecord
  extend FriendlyId

  before_validation :generate_token, on: :create
  after_create :create_default_positions
  after_save :trigger_webhooks
  after_touch :trigger_webhooks
  before_destroy :destroy_icon

  has_many :authorized_users, dependent: :destroy
  has_many :users, through: :authorized_users
  has_many :projects, dependent: :destroy
  has_many :all_shows, through: :projects
  has_many :positions, -> { order(rank: :asc) }, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :webhooks, dependent: :destroy
  has_one_attached :icon

  validates :name, presence: true,
                   uniqueness: true

  validates :acronym, presence: true,
                      uniqueness: true

  validates :token, presence: true,
                    uniqueness: true

  validates :icon, blob: {
                    content_type: :image,
                    size_range: 0..1.megabytes }

  friendly_id :name, use: :slugged


  def generate_token
    new_token = loop do
      token = SecureRandom.urlsafe_base64
      break token unless Group.exists?(token: token)
    end

    self.token = new_token
  end

  def fullname
    "[#{acronym}] #{name}"
  end

  def shows
    Show.joins(:projects).where(projects: { group: self, status: :accepted })
  end

  def priority_show_search!(name)
    result = shows.visible.joins(:terms).where('lower(terms.name) = ?', name.downcase).first
    return result unless result.nil?

    results = shows.visible.where('lower(shows.name) LIKE ?', "%#{ApplicationRecord::sanitize_sql_like(name.downcase)}%")

    case results.length
    when 0
      raise ShowNotFoundError
    when 1
      return results.first
    else
      return results.airing.first if results.airing.length == 1
      return results.active.first if results.active.length == 1

      names = results.map(&:name).to_sentence
      raise MultipleMatchingShowsError, "Multiple show matches: #{names}"
    end
  end

  private
    def create_default_positions
      Position.create([
        { name: "Translator", acronym: "TL", group: self },
        { name: "Translation Checker", acronym: "TLC", group: self },
        { name: "Editor", acronym: "ED", group: self },
        { name: "Timer", acronym: "TM", group: self },
        { name: "Typesetter", acronym: "TS", group: self },
        { name: "Encoder", acronym: "ENC", group: self },
        { name: "Quality Control", acronym: "QC", group: self }
      ])
    end

    def destroy_icon
      icon.purge_later
    end

    def trigger_webhooks
      webhooks.vercel.each do |webhook|
        # VercelWebhookJob.perform_later(webhook)
        Net::HTTP.post(URI(webhook.url), nil)
      end
    end
end

app/controllers/api/v1/groups_controller.rb
module Api
  module V1
    class GroupsController < ApplicationController
      include ErrorHandler

      respond_to :json
      protect_from_forgery with: :null_session

      def index
        @groups = Group.all.order(id: :asc)
      end

      def show
        @group = Group.find_by!(token: params[:token])
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_group!, only: [:show, :update, :destroy]

  before_action do
    add_breadcrumb "Groups", groups_url
  end

  def index
    @groups = current_user.groups
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      # Add logged in user to the group
      AuthorizedUser.create(user: current_user, group: @group, owner: true)

      redirect_to @group
    else
      render 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_url(@group), notice: "#{@group.name} Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: "#{@group.name} has been deleted."
  end

  private
    def set_group
      @group = current_user.groups.friendly.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:name, :acronym, :icon)
    end
end

app/views/groups/_form.html.erb
<%= form_with model: @group, local: true do |f| %>
  <h3 class="text-lg leading-6 font-medium text-gray-900">
    Information
  </h3>
  <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
    Group names and acronyms must be unique. Webhooks will use your icon as the message avatar.
  </p>

  <%= render partial: "layouts/errors", locals: { record: @group } %>

  <div class="mt-12">
    <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start">
      <%= f.label :name, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.text_field :name, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :acronym, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <%# <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs"> %>
        <div class="max-w-lg sm:max-w-xs">
          <%= render partial: 'forms/text_input', locals: { f: f, record: @group, key: :acronym } %>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-center sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :icon, class: "block text-sm font-medium leading-5 text-gray-700" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.file_field :icon, accept: 'image/png,image/jpeg', direct_upload: true, class: "max-w-full py-2 px-3 border border-gray-300 rounded-md text-sm leading-4 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
        </div>
        <p class="text-sm pt-1 text-gray-500">1mb Max Size</p>
      </div>
    </div>

  </div>
  <div class="mt-8 border-t border-gray-200 pt-5">
    <div class="flex justify-end">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to "Cancel", groups_url, class: "py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
      </span>
      <% unless @group.new_record? %>
        <span class="ml-3 inline-flex rounded-md shadow-sm">
          <%= link_to "Delete Group", group_url(@group), method: :delete, data: { confirm: "Are you sure you wish to delete this group? This action is irreversible." }, class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out" %>
        </span>
      <% end %>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <%= f.submit @group.new_record? ? "Create Group" : "Edit Group", class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out" %>
      </span>
    </div>
  </div>
<% end %>

app/views/groups/_group.html.erb
<li class="py-10 px-6 bg-gray-800 text-center rounded-lg xl:px-10 xl:text-left">
  <%= link_to group_url(group) do %>
    <div class="space-y-6 xl:space-y-10">
      <div class="w-full flex justify-center">
        <%= render partial: 'groups/icon', locals: { group: group } %>
      </div>
      <div class="space-y-2 xl:flex xl:items-center xl:justify-between">
        <div class="font-medium text-lg leading-6 space-y-1">
          <h4 class="text-white"><%= group.fullname %></h4>
          <p class="text-indigo-400"><%= pluralize(group.shows.active.count, "Active Show") %>, <%= group.shows.count %> Total</p>
        </div>
      </div>
    </div>
  <% end %>
</li>

app/views/groups/_icon.html.erb
<% width = "w-40" if local_assigns[:width].nil? %>
<% height = "h-40" if local_assigns[:height].nil? %>

<% if group.icon.attached? %>
  <%= image_tag url_for(group.icon), alt: "#{group.name} Icon", class: "#{height} #{width} rounded-full" %>
<% else %>
  <div class="flex items-center">
    <span class="mx-auto <%= height || "h-40" %> <%= width || "w-40" %> rounded-full overflow-hidden bg-gray-100">
      <svg class="h-full w-full text-gray-300" fill="currentColor" viewBox="0 0 24 24">
        <path d="M24 20.993V24H0v-2.996A14.977 14.977 0 0112.004 15c4.904 0 9.26 2.354 11.996 5.993zM16.002 8.999a4 4 0 11-8 0 4 4 0 018 0z" />
      </svg>
    </span>
  </div>
<% end %>

app/views/groups/edit.html.erb
<% content_for :title, 'Edit Group' %>

<%= render partial: 'groups/form' %>

app/views/groups/index.html.erb
<% content_for :title, 'My Groups' %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Create Group', url: new_group_url, highlight: true }]}  %>
<% end %>


<div class="mx-auto py-8 px-4 max-w-screen-xl sm:px-6 lg:px-8">
  <div class="space-y-12">
    <% if @groups.empty? %>
      <%= render partial: 'layouts/empty', locals: { content: "You don't have any Groups!" } %>
    <% else %>
      <ul class="space-y-4 sm:grid sm:grid-cols-2 sm:gap-6 sm:space-y-0 lg:grid-cols-3 lg:gap-8">
        <%= render partial: 'groups/group', collection: @groups, cached: true %>
      </ul>
    <% end %>
  </div>
</div>

app/views/groups/new.html.erb
<% content_for :title, 'Create New Group' %>

<%= render partial: 'groups/form' %>

app/views/groups/show.html.erb
<% content_for :title, @group.name %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Edit Group', url: edit_group_url(@group), highlight: true }]}  %>
<% end %>

<div class="w-full grid grid-cols-1 gap-5 sm:grid-cols-2">
  <div class="flex justify-start items-center space-x-4 lg:space-x-6">
    <%= render partial: 'groups/icon', locals: { group: @group } %>
    <div class="font-medium text-2xl leading-6 space-y-1">
      <h4 class="text-indigo-600"><%= @group.name %></h4>
      <p>[<%= @group.acronym %>]</p>
    </div>
  </div>

  <div class="bg-gray-50 sm:rounded-lg" data-controller="clipboard">
    <div class="px-4 py-5 sm:p-6">
      <h3 class="text-lg leading-6 font-medium text-gray-900">
        Token
      </h3>
      <div class="mt-2 max-w-xl text-sm leading-5 text-gray-500">
        <p>
          Use this with bots (such as <%= link_to "Aquarius", documentation_discord_url, class: "text-indigo-600 hover:text-indigo-500 focus:outline-none focus:underline transition ease-in-out duration-150" %>) to interact with Deschtimes.
        </p>
      </div>
      <div class="mt-5">
        <p class="font-mono" data-target="clipboard.source"><%= @group.token %></p>
      </div>
      <div class="mt-5">
        <span class="inline-flex rounded-md shadow-sm">
          <%= link_to "Regenerate", group_token_url(@group), method: :put, data: { confirm: "Regenerating your token will invalidate the current one. Continue?" }, class: "inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:text-gray-800 active:bg-gray-50 transition ease-in-out duration-150" %>
        </span>
        <span class="ml-3inline-flex rounded-md shadow-sm">
          <button data-action="clipboard#copy" data-target="clipboard.button" class="inline-flex items-center px-4 py-2 border border-gray-300 text-sm leading-5 font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:text-gray-800 active:bg-gray-50 transition ease-in-out duration-150">Copy</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="mt-8 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
  <%= link_to group_shows_url(@group), class: "block bg-white overflow-hidden shadow rounded-lg" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 4v16M17 4v16M3 8h4m10 0h4M3 12h18M3 16h4m10 0h4M4 20h16a1 1 0 001-1V5a1 1 0 00-1-1H4a1 1 0 00-1 1v14a1 1 0 001 1z" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Shows
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.shows.count %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>

  <%= link_to group_members_url(@group), class: "block bg-white overflow-hidden shadow rounded-lg" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4.354a4 4 0 110 5.292M15 21H3v-1a6 6 0 0112 0v1zm0 0h6v-1a6 6 0 00-9-5.197M13 7a4 4 0 11-8 0 4 4 0 018 0z" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Total Members
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.members.size %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>

  <%= link_to group_positions_url(@group), class: "bg-white overflow-hidden shadow rounded-lg block" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Positions
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.positions.size %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5" data-controller="confirmable">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>

  <%= link_to group_webhooks_url(@group), class: "block bg-white overflow-hidden shadow rounded-lg" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Webhooks
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.webhooks.count %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>

  <%= link_to group_users_url(@group), class: "block bg-white overflow-hidden shadow rounded-lg" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 7a2 2 0 012 2m4 0a6 6 0 01-7.743 5.743L11 17H9v2H7v2H4a1 1 0 01-1-1v-2.586a1 1 0 01.293-.707l5.964-5.964A6 6 0 1121 9z" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Authorized Users
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.users.count %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>

    <%= link_to group_projects_url(@group), class: "block bg-white overflow-hidden shadow rounded-lg" do %>
    <div class="px-4 py-5 sm:p-6">
      <div class="flex items-center">
        <div class="flex-shrink-0 bg-indigo-500 rounded-md p-3">
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
          </svg>
        </div>
        <div class="ml-5 w-0 flex-1">
          <dl>
            <dt class="text-sm leading-5 font-medium text-gray-500 truncate">
              Pending Joint Invitations
            </dt>
            <dd class="flex items-baseline">
              <div class="text-2xl leading-8 font-semibold text-gray-900">
                <%= @group.projects.where(status: :pending).count %>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-4 sm:px-6">
      <div class="text-sm leading-5">
        <span class="font-medium text-indigo-600">Manage</span>
      </div>
    </div>
  <% end %>
</div>