config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :groups, only: [:index, :show], param: :token do
        resources :shows, only: [:index, :show], param: :name do
          patch 'episodes', to: 'episodes#update'
          patch 'staff', to: 'staff#update'
        end
      end
    end
  end

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  resources :groups do
    resources :shows do
      resources :episodes do
        resources :staff, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :terms, only: [:new, :create, :destroy]
      resources :projects, only: [:new, :create, :update, :destroy]
    end

    resources :tokens, only: [:update]
    resources :members, except: [:show]
    resources :users, except: [:edit, :update]
    resources :webhooks, except: [:show]
    resources :positions, except: [:show]
    resources :projects, only: [:index]
  end

  get 'donations', to: 'donations#index'
  get 'documentation', to: 'documentation#index'
  get 'documentation/discord', to: 'documentation#discord'
  get 'documentation/api', to: 'documentation#api'
  get 'documentation/webhooks', to: 'documentation#webhooks'
end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id         :bigint           not null, primary key
#  air_date   :datetime
#  number     :integer
#  released   :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  show_id    :bigint           not null
#
# Indexes
#
#  index_episodes_on_released  (released)
#  index_episodes_on_show_id   (show_id)
#
# Foreign Keys
#
#  fk_rails_...  (show_id => shows.id)
#
require 'action_view'
require 'action_view/helpers'
include ActionView::Helpers::DateHelper

class Episode < ApplicationRecord
  has_many :staff, -> { joins(:position).order(rank: :asc) }, dependent: :destroy
  belongs_to :show, touch: true

  after_update :notify_release, if: :saved_change_to_released?

  attr_accessor :update_air_dates

  accepts_nested_attributes_for :staff

  scope :pending, -> { where(released: false) }
  scope :released, -> { where(released: true) }

  validates :show, presence: true

  validates :air_date, presence: true

  validates :number, presence: true,
                     numericality: true,
                     uniqueness: {
                       scope: :show,
                       message: "Show episode number must be unique"
                     }

  def season
    "#{Episode.month_to_season(air_date.month)} #{air_date.year}"
  end

  def aired?
    air_date <= DateTime.now
  end

  def remaining_staff_positions
    unfinished = staff.where(finished: false)

    if unfinished.size > 0
      unfinished.map(&:position).map(&:acronym).to_sentence
    else
      "None!"
    end
  end

  def discord_status_label
    staff.map do |staff|
      key = staff.position.acronym
      staff.finished ? "~~#{key}~~" : "**#{key}**"
    end
  end

  def find_staff_for_member_and_position!(member, positions, finished)
    results = staff.where(position: positions).reorder(id: :asc).distinct
    raise EpisodePositionStaffNotFoundError if results.empty?

    results = results.where(member: member) unless member.admin?

    case results.size
    when 0
      raise StaffNotFoundError
    when 1
      return results.first
    else
      # Prioritize specific job
      job = results.where(member: member, finished: !finished).first
      return job unless job.nil?

      # Prioritize in-group positions
      job = results.includes(:position).where(finished: !finished, position: { group: member.group }).first
      return job unless job.nil?

      # Return first matching results
      return results.where(finished: !finished).first
    end
  end

  private
    def self.month_to_season(month)
      case month
      when 1..3
        "Winter"
      when 4..6
        "Spring"
      when 7..9
        "Summer"
      when 10..12
        "Fall"
      end
    end

    def notify_release
      return unless self.released?
      return unless show.visible?

      released = show.episodes.where(released: true).size
      unreleased = show.episodes.where(released: false).size

      episode = self
      thumbnail = Rails.application.routes.url_helpers.rails_blob_url(episode.show.poster, disposition: "attachment") if episode.show.poster.attached?

      embed = Discord::Embed.new do
        title "#{episode.show.name} Episode ##{episode.number} Released!"
        color 0x008000
        timestamp DateTime.now
        thumbnail url: thumbnail
        author name: 'Deschtimes',
               url: 'https://deschtimes.com'

        description episode.show.status if episode.show.status?
      end

      if show.current_unreleased_episode&.aired?
        embed.add_field name: "Episode ##{show.current_unreleased_episode.number} Status",
                        value: show.current_unreleased_episode.discord_status_label.join(" ")
      elsif show.current_unreleased_episode
        embed.add_field name: 'Next Air Date',
                        value: distance_of_time_in_words(DateTime.now, show.current_unreleased_episode.air_date)
      else
        embed.add_field name: 'Fansub Finished!',
                        value: 'This was the last episode in the series!'
      end

      Webhook.discord.where(group: show.groups).each do |webhook|
        avatar = nil

        if webhook.group.icon.attached?
          avatar = Rails.application.routes.url_helpers.rails_blob_url(webhook.group.icon, disposition: "attachment")
        end

        # DiscordWebhookJob.perform_later(webhook, embed.to_json, avatar)
        Discord::Notifier.message embed,
                                  username: webhook.name,
                                  url: webhook.url,
                                  avatar_url: avatar
      end
    end
end

app/controllers/api/v1/episodes_controller.rb
module Api
  module V1
    class EpisodesController < ApplicationController
      include ErrorHandler
      include ApiResponses

      respond_to :json
      protect_from_forgery with: :null_session

      def update
        @group = Group.find_by!(token: params[:group_token])
        @show = @group.priority_show_search!(URI.decode_www_form_component(params[:show_name]))
        @member = @group.members.find_by(discord: params[:member])

        raise MemberNotFoundError if @member.nil?
        raise InsufficientPermissionsError unless @member.admin?
        raise ShowFinishedError if @show.finished?

        unfinished_staff = @show.current_unreleased_episode.staff.where(finished: false)
        if unfinished_staff.present?
          positions = unfinished_staff.map { |staff| staff.position.name }
          raise EpisodeStaffIncompleteError, "The #{positions.to_sentence} positions are still incomplete!"
        end

        @show.current_unreleased_episode.update(released: true)
        @show = Show.includes(episodes: [staff: [:position, member: [:group]]]).find(@show.id)
        render 'api/v1/shows/show'
      end
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action do
    authenticate_user!
    set_group
    set_show

    add_breadcrumb "Groups", groups_url
    add_breadcrumb @group.name, group_url(@group)
    add_breadcrumb "Shows", group_shows_url(@group)
    add_breadcrumb @show.name, group_show_url(@group, @show)
  end

  def index
    @episodes = @show.episodes.includes(staff: :position)
  end

  def show
    add_breadcrumb "Episodes", group_show_episodes_url(@group, @show)

    @episode = @show.episodes.includes(staff: [:position, member: [:group]]).find(params[:id])
  end

  def new
    @episode = Episode.new(
      number: (@show.last_episode&.number || 0) + 1,
      air_date: (@show.last_episode&.air_date || DateTime.now) + 1.week
    )
  end

  def create
    @episode = Episode.new(episode_params)
    @episode.show = @show

    if @episode.save
      redirect_to group_show_episodes_url(@group, @show)
    else
      render 'new'
    end
  end

  def edit
    @episode = @show.episodes.find(params[:id])
    add_breadcrumb "Episodes", group_show_episodes_url(@group, @show)
  end

  def update
    @episode = @show.episodes.find(params[:id])

    if @episode.update(episode_params)
      if ActiveRecord::Type::Boolean.new.deserialize(params[:episode][:update_air_dates])
        @show.reschedule_episodes(@episode)
      end

      redirect_to group_show_episode_url(@group, @show, @episode), notice: "#{@show.name} episode #{@episode.number} Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @episode = @show.episodes.find(params[:id])

    if @episode.destroy
      redirect_to group_show_episodes_url(@group, @show), notice: "#{@show.name} episode #{@episode.number} Deleted"
    else
      redirect_to group_show_episode_url(@group, @show, @episode), notice: "#{@show.name} episode #{@episode.number} could not be deleted."
    end
  end

  private
  def episode_params
    params.require(:episode).permit(:number, :released, :air_date, :update_air_dates)
  end
end

app/views/episodes/edit.html.erb
<% content_for :title, "Edit #{@show.name} episode #{@episode.number}" %>

<%= form_with model: [@group, @show, @episode], local: true, html: { multipart: true } do |f| %>

  <%= render partial: "layouts/errors", locals: { record: @episode } %>

  <div class="mt-6 sm:mt-5">
    <div class="mt-6 sm:mt-5">
      <div class="sm:border-t sm:border-gray-200 sm:pt-5">
        <div role="group" aria-labelledby="label-email">
          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
            <div>
              <div class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700" id="label-email">
                Released
              </div>
            </div>
            <div class="mt-4 sm:mt-0 sm:col-span-2">
              <div class="max-w-lg">
                <div class="relative flex items-start">
                  <div class="flex items-center h-5">
                    <%= f.check_box :released, { class: "form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out" } %>
                  </div>
                  <div class="ml-3 text-sm leading-5">
                    <%= f.label :released, class: "font-medium text-gray-700" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :number, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.number_field :number, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :air_date, "Air Date", class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.datetime_field :air_date, class: "js-datetime-picker form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
        <p class="text-sm pt-1 text-gray-500">Timezone is JST.</p>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:mt-5">
      <div class="sm:border-t sm:border-gray-200 sm:pt-5">
        <div role="group" aria-labelledby="label-email">
          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
            <div>
              <div class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700" id="label-email">
                Update Air Dates
              </div>
            </div>
            <div class="mt-4 sm:mt-0 sm:col-span-2">
              <div class="max-w-lg">
                <div class="relative flex items-start">
                  <div class="flex items-center h-5">
                    <%= f.check_box :update_air_dates, { checked: false, class: "form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out" } %>
                  </div>
                  <div class="ml-3 text-sm leading-5">
                    <%= f.label :update_air_dates, class: "font-medium text-gray-700" %>
                    <p class="text-gray-500">This automatically sets future episodes to use this time weekly from the selected date on.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="mt-8 border-t border-gray-200 pt-5">
    <div class="flex justify-end">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to "Cancel", group_show_episode_url(@group, @show, @episode), class: "py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <%= link_to "Delete Episode", group_show_episode_url(@group, @show, @episode), method: :delete, data: { confirm: "Are you sure you wish to delete this episode? This action is irreversible." }, class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
          Update Episode
        </button>
      </span>
    </div>
  </div>
<% end %>

app/views/episodes/index.html.erb
<% content_for :title, 'Episodes' %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Add Episode', url: new_group_show_episode_url(@group, @show), highlight: true }]}  %>
<% end %>

<div class="bg-white shadow overflow-hidden sm:rounded-md">
  <ul>
    <% @episodes.each_with_index do |episode, index| %>
      <li class="<%= index > 0 ? "border-t border-gray-200" : "" %>">
        <%= link_to group_show_episode_url(@group, @show, episode), class: "block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out" do %>
          <div class="px-4 py-4 sm:px-6">
            <div class="flex items-center justify-between">
              <div class="text-sm leading-5 font-medium text-indigo-600 truncate">
                Episode <%= episode.number %>
              </div>
              <div class="ml-2 flex-shrink-0 flex">
                <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full <%= episode.released ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800" %>">
                  <%= episode.released ? "Released" : "Unreleased" %>
                </span>
              </div>
            </div>
            <div class="mt-2 sm:flex sm:justify-between">
              <div class="sm:flex">
                <div class="mr-6 flex items-center text-sm leading-5 text-gray-500">
                  <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M9 6a3 3 0 11-6 0 3 3 0 016 0zM17 6a3 3 0 11-6 0 3 3 0 016 0zM12.93 17c.046-.327.07-.66.07-1a6.97 6.97 0 00-1.5-4.33A5 5 0 0119 16v1h-6.07zM6 11a5 5 0 015 5v1H1v-1a5 5 0 015-5z" />
                  </svg>
                  Remaining staff: <%= episode.remaining_staff_positions %>
                </div>
                <div class="mr-6 flex items-center text-sm leading-5 text-gray-500">
                  <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  Updated: <span class="ml-1"><%= local_time_ago(episode.updated_at) %></span>
                </div>
              </div>
              <div class="mt-2 flex items-center text-sm leading-5 text-gray-500 sm:mt-0">
                <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clip-rule="evenodd" />
                </svg>
                <span>
                  <% if episode.released %>
                    Released!
                  <% elsif episode.aired? %>
                    Aired <%= local_time(episode.air_date) %>
                  <% else %>
                    Airs on <%= local_time(episode.air_date) %>
                  <% end %>
                </span>
              </div>
            </div>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/episodes/new.html.erb
<% content_for :title, "Add #{@show.name} episode" %>

<%= form_with model: [@group, @show, @episode], local: true, html: { multipart: true } do |f| %>

  <%= render partial: "layouts/errors", locals: { record: @show } %>

  <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <%= f.label :number, "Episode Number", class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
        <%= f.number_field :number, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
    <%= f.label :air_date, "Air Date", class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
    <div class="mt-1 sm:mt-0 sm:col-span-2">
      <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
        <%= f.datetime_field :air_date, class: "js-datetime-picker form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
      </div>
    </div>
  </div>

  <div class="mt-6 sm:mt-5">
    <div class="mt-6 sm:mt-5">
      <div class="sm:border-t sm:border-gray-200 sm:pt-5">
        <div role="group" aria-labelledby="label-email">
          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
            <div>
              <div class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700" id="label-email">
                Released
              </div>
            </div>
            <div class="mt-4 sm:mt-0 sm:col-span-2">
              <div class="max-w-lg">
                <div class="relative flex items-start">
                  <div class="flex items-center h-5">
                    <%= f.check_box :released, { class: "form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out" } %>
                  </div>
                  <div class="ml-3 text-sm leading-5">
                    <%= f.label :released, class: "font-medium text-gray-700" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="mt-8 border-t border-gray-200 pt-5">
    <div class="flex justify-end">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to "Cancel", group_show_episodes_url(@group, @show), class: "py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
          Add Episode
        </button>
      </span>
    </div>
  </div>
<% end %>

app/views/episodes/show.html.erb
<% content_for :title, "Episode #{@episode.number}" %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Add Staff', url: new_group_show_episode_staff_url(@group, @show, @episode) }, { name: 'Edit Episode', url: edit_group_show_episode_url(@group, @show, @episode), highlight: true }]}  %>
<% end %>

<dl class="sm:divide-y sm:divide-gray-200">
  <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
    <dt class="text-sm font-medium text-gray-500">
      Released
    </dt>
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
      <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full <%= @episode.released ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800" %>">
        <%= @episode.released ? "Released" : "Unreleased" %>
      </span>
    </dd>
  </div>
  <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
    <dt class="text-sm font-medium text-gray-500">
      Air Date
    </dt>
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
      <%= @episode.air_date %>
    </dd>
  </div>
  <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
    <dt class="text-sm font-medium text-gray-500">
      Last Update
    </dt>
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
      <%= local_time(@episode.updated_at) %>
    </dd>
  </div>

  <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4">
    <dt class="text-sm font-medium text-gray-500">
      Staff
    </dt>
    <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
      <ul class="border border-gray-200 rounded-md divide-y divide-gray-200">
        <% @episode.staff.each do |staff| %>
          <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm">
            <div class="w-0 flex-1 flex items-center">
              <% if staff.finished %>
                <svg class="flex-shrink-0 h-5 w-5 text-green-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              <% else %>
                <svg class="flex-shrink-0 h-5 w-5 text-red-600" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              <% end %>
              <span class="ml-2 flex-1 w-0 truncate">
                <%= staff.title(@show.joint?) %>
              </span>
            </div>
            <div class="ml-4 flex-shrink-0 flex space-x-4">
              <%= link_to "Update", edit_group_show_episode_staff_url(@group, @show, @episode, staff), class: "bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
              <span class="text-gray-300" aria-hidden="true">|</span>
              <%= link_to "Remove", group_show_episode_staff_url(@group, @show, @episode, staff), method: :delete, data: { confirm: "Do you wish to remove\"#{staff.title(@show.joint?)}\"?" }, class: "bg-white rounded-md font-medium text-red-600 hover:text-red-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500" %>
            </div>
          </li>
        <% end %>
      </ul>
    </dd>
  </div>
</dl>