config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  root to: 'home#index'

  namespace :api do
    namespace :v1 do
      resources :groups, only: [:index, :show], param: :token do
        resources :shows, only: [:index, :show], param: :name do
          patch 'episodes', to: 'episodes#update'
          patch 'staff', to: 'staff#update'
        end
      end
    end
  end

  devise_for :users, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'register'
  }

  resources :groups do
    resources :shows do
      resources :episodes do
        resources :staff, only: [:new, :create, :edit, :update, :destroy]
      end

      resources :terms, only: [:new, :create, :destroy]
      resources :projects, only: [:new, :create, :update, :destroy]
    end

    resources :tokens, only: [:update]
    resources :members, except: [:show]
    resources :users, except: [:edit, :update]
    resources :webhooks, except: [:show]
    resources :positions, except: [:show]
    resources :projects, only: [:index]
  end

  get 'donations', to: 'donations#index'
  get 'documentation', to: 'documentation#index'
  get 'documentation/discord', to: 'documentation#discord'
  get 'documentation/api', to: 'documentation#api'
  get 'documentation/webhooks', to: 'documentation#webhooks'
end

app/models/show.rb
# == Schema Information
#
# Table name: shows
#
#  id             :bigint           not null, primary key
#  name           :string
#  projects_count :integer          default(0), not null
#  status         :text
#  visible        :boolean
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_shows_on_name     (name)
#  index_shows_on_visible  (visible)
#
class Show < ApplicationRecord
  include NormalizeBlankValues

  after_create :create_episodes
  before_save :touch_groups
  after_touch :touch_groups
  before_destroy :destroy_poster

  attr_accessor :new_show_episode_count
  attr_accessor :new_show_episode_air_date
  attr_accessor :new_show_episode_number_start
  attr_accessor :new_show_staff
  attr_accessor :new_show_group

  has_many :projects, dependent: :destroy
  has_many :all_groups, through: :projects
  has_many :terms, dependent: :destroy
  has_many :episodes, -> { order(number: :asc) }, dependent: :destroy
  has_one_attached :poster

  validates :name, presence: true

  validates :poster, blob: {
                      content_type: :image,
                      size_range: 0..1.megabytes }

  scope :visible, -> { where(visible: true) }

  scope :active, -> {
    includes(:episodes)
      .where(episodes: { released: false })
      .order("episodes.air_date DESC")
  }

  scope :finished, -> {
    where.not(id: Episode.select(:show_id).where(released: false))
  }

  scope :airing, -> {
    joins(:episodes)
      .merge(
        Episode.where('air_date >= :current_date', current_date: DateTime.now)
      )
      .distinct
  }

  def groups
    Group.joins(:projects).where(projects: { show: self, status: :accepted })
  end

  def next_airing_episode
    episodes.where('air_date >= :current_date', current_date: DateTime.now)
      .order(number: :asc)
      .first
  end

  def first_episode
    episodes.first
  end

  def last_episode
    episodes.reorder(number: :desc).first
  end

  def reschedule_episodes(episode)
    episodes.where("number > ?", episode.number).order(number: :asc).each_with_index do |ep, index|
      ep.update(air_date: episode.air_date + (1 + index).weeks)
    end
  end

  def season
    season_start = first_episode&.season
    season_end = last_episode&.season

    if season_start == season_end
      season_start
    else
      "#{season_start} to #{season_end}"
    end
  end

  def current_unreleased_episode
    episodes.pending.order("episodes.number ASC").first
  end

  def progress_label
    if airing?
      "Airing"
    elsif finished?
      "Complete"
    else
      "Incomplete"
    end
  end

  def airing?
    episodes.where('air_date >= :current_date', current_date: DateTime.now).any?
  end

  def joint?
    groups.count > 1
  end

  def finished?
    current_unreleased_episode.nil?
  end

  private
    # When a show is finished, we need to update counters on various UI elements.
    # To do this, we need to bust the cache
    def touch_groups
      groups.each { |group| group.touch }
    end

    def destroy_poster
      poster.purge_later
    end

    def create_episodes
      group = new_show_group
      offset = new_show_episode_number_start.to_i.abs
      air_date = Time.find_zone("Japan").parse(new_show_episode_air_date) || DateTime.now

      new_show_episode_count.to_i.clamp(1, 5_000).times do |index|
        episode = Episode.create(
          show: self,
          number: index + offset,
          air_date: air_date + 1.week * index
        )

        (new_show_staff || []).each do |staff|
          begin
            Staff.create(
              member: group.members.find(staff["member"].to_i),
              position: group.positions.find(staff["position"].to_i),
              episode: episode
            )
          rescue => e
            # Likely empty staff; just allow to fail silently
          end
        end
      end

      save
    end
end

app/controllers/api/v1/shows_controller.rb
module Api
  module V1
    class Api::V1::ShowsController < ApplicationController
      include ErrorHandler

      respond_to :json
      protect_from_forgery with: :null_session

      def index
        @group = Group.find_by!(token: params[:group_token])
      end

      def show
        @group = Group.find_by!(token: params[:group_token])
        @show = Show.includes(episodes: [staff: [:position, member: [:group]]]).find(@group.priority_show_search!(URI.decode_www_form_component(params[:name])).id)
      end
    end
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action do
    authenticate_user!
    set_group

    add_breadcrumb "Groups", groups_url
    add_breadcrumb @group.name, group_url(@group)
  end

  def index
    shows = @group.shows.with_attached_poster.includes(:episodes)
    @airing = shows.airing
    @active = shows.active.where.not(id: @airing)
    @finished = shows.finished
  end

  def show
    add_breadcrumb "Shows", group_shows_url(@group)

    @show = @group.shows.find(params[:id])
  end

  def new
    add_breadcrumb "Shows", group_shows_url(@group)

    @show = Show.new
  end

  def create
    @show = Show.new(show_params)
    @show.new_show_group = @group

    if @show.save
      Project.create(group: @group, show: @show, status: :accepted)
      redirect_to group_show_url(@group, @show)
    else
      # TODO: Prevents a weird string bug. Probably a better way of handling this
      @show.new_show_episode_air_date = @show.new_show_episode_air_date.to_datetime || DateTime.now

      render 'new'
    end
  end

  def edit
    @show = @group.shows.find(params[:id])
    add_breadcrumb "Shows", group_shows_url(@group)
  end

  def update
    @show = @group.shows.find(params[:id])

    if @show.update(show_params)
      redirect_to group_show_url(@group, @show), notice: "#{@show.name} Updated"
    else
      render 'edit'
    end
  end

  def destroy
    @show = @group.shows.find(params[:id])

    if @show.destroy
      redirect_to group_shows_url(@group), notice: "Show `#{@show.name}` removed."
    else
      redirect_to group_show_url(@group, @show), alert: "Show could not be removed."
    end
  end

  private
    def show_params
      params.require(:show).permit(:name, :poster, :visible, :status, :new_show_episode_count, :new_show_episode_air_date, :new_show_episode_number_start, new_show_staff: [:position, :member])
    end
end

app/views/shows/_show.html.erb
<li>
  <div class="space-y-4 sm:grid sm:grid-cols-3 sm:gap-6 sm:space-y-0 lg:gap-8">
    <div class="relative h-0 pb-2/3 sm:pt-2/3">
      <%= link_to group_show_url(@group, show) do %>
        <% if show.poster.attached? %>
          <%= image_tag url_for(show.poster), alt: "#{show.name} Poster", class: "absolute inset-0 object-cover h-full w-full shadow-lg rounded-lg" %>
        <% else %>
          <div class="absolute inset-0 object-cover h-full w-full shadow-lg rounded-lg bg-gradient-to-r from-orange-400 via-red-500 to-pink-500"></div>
        <% end %>
      <% end %>
    </div>
    <div class="sm:col-span-2">
      <div class="space-y-4">
        <div class="text-lg leading-6 font-medium space-y-1">
          <h4 class="text-indigo-600">
            <%= link_to group_show_url(@group, show) do %>
              <% unless show.visible? %>
                <svg class="w-5 h-5 inline mr-1 -mt-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
              </svg>
              <% end %>
              <%= show.name %>
            <% end %>
          </h4>
          <% if show.finished? %>
            <p><%= pluralize show.episodes.size, "episode" %> released!</p>
          <% else %>
            <p>Episode <%= show.current_unreleased_episode&.number || '-' %>/<%= show.last_episode&.number || '-' %></p>
          <% end %>
        </div>
        <div class="text-lg text-gray-500 leading-7">
          <p><%= show.status || "There is no status message." %></p>
          <p class="text-sm">Last updated <%= local_time_ago(show.updated_at) %>.</p>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/shows/edit.html.erb
<% content_for :title, "Edit #{@show.name}" %>

<%= form_with model: [@group, @show], local: true, html: { multipart: true } do |f| %>
  <h3 class="text-lg leading-6 font-medium text-gray-900">
    Show Information
  </h3>
  <p class="mt-1 max-w-2xl text-sm leading-5 text-gray-500">
    Positions track the different roles members will be assigned while working on a Show.
  </p>

  <%= render partial: "layouts/errors", locals: { record: @show } %>

  <div class="mt-6 sm:mt-5">
    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-start sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :name, class: "block text-sm font-medium leading-5 text-gray-700 sm:mt-px sm:pt-2" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.text_field :name, class: "form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-center sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :poster, class: "block text-sm font-medium leading-5 text-gray-700" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.file_field :poster, accept: "image/png,image/jpeg", direct_upload: true, class: "max-w-full py-2 px-3 border border-gray-300 rounded-md text-sm leading-4 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
        </div>
        <p class="text-sm pt-1 text-gray-500">1mb Max Size</p>
      </div>
    </div>

    <div class="mt-6 sm:mt-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:items-center sm:border-t sm:border-gray-200 sm:pt-5">
      <%= f.label :status, class: "block text-sm font-medium leading-5 text-gray-700" %>
      <div class="mt-1 sm:mt-0 sm:col-span-2">
        <div class="max-w-lg rounded-md shadow-sm sm:max-w-xs">
          <%= f.text_area :status, class: "form-textarea block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5" %>
        </div>
      </div>
    </div>


    <div class="mt-6 sm:mt-5">
      <div class="sm:border-t sm:border-gray-200 sm:pt-5">
        <div role="group" aria-labelledby="label-email">
          <div class="sm:grid sm:grid-cols-3 sm:gap-4 sm:items-baseline">
            <div>
              <div class="text-base leading-6 font-medium text-gray-900 sm:text-sm sm:leading-5 sm:text-gray-700" id="label-email">
                Visibility
              </div>
            </div>
            <div class="mt-4 sm:mt-0 sm:col-span-2">
              <div class="max-w-lg">
                <div class="relative flex items-start">
                  <div class="flex items-center h-5">
                    <%= f.check_box :visible, { checked: true, class: "form-checkbox h-4 w-4 text-indigo-600 transition duration-150 ease-in-out" } %>
                  </div>
                  <div class="ml-3 text-sm leading-5">
                    <%= f.label :visible, class: "font-medium text-gray-700" %>
                    <p class="text-gray-500">This show will appear in API results and be publicly visible by users.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="mt-8 border-t border-gray-200 pt-5">
    <div class="flex justify-end">
      <span class="inline-flex rounded-md shadow-sm">
        <%= link_to "Cancel", group_show_url(@group, @show), class: "py-2 px-4 border border-gray-300 rounded-md text-sm leading-5 font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-50 active:text-gray-800 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <%= link_to "Delete Show", group_show_url(@group, @show), method: :delete, data: { confirm: "Are you sure you wish to delete this show? This action is irreversible." }, class: "inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-red-600 hover:bg-red-500 focus:outline-none focus:border-red-700 focus:shadow-outline-red active:bg-red-700 transition duration-150 ease-in-out" %>
      </span>
      <span class="ml-3 inline-flex rounded-md shadow-sm">
        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
          Update Show
        </button>
      </span>
    </div>
  </div>
<% end %>

app/views/shows/index.html.erb
<% content_for :title, 'Shows' %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [{ name: 'Add Show', url: new_group_show_url(@group), highlight: true }]}  %>
<% end %>

<% if @group.projects.where(status: :pending).size > 0 %>
  <div class="rounded-md bg-blue-50 p-4 mt-4">
    <div class="flex">
      <div class="flex-shrink-0">
        <svg class="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3 flex-1 md:flex md:justify-between">
        <p class="text-sm leading-5 text-blue-700">
          You have <%= pluralize(@group.projects.where(status: :pending).size, "pending invitation") %> to work on a joint project!
        </p>
        <p class="mt-3 text-sm md:mt-0 md:ml-6">
          <%= link_to group_projects_url(@group), class: "whitespace-nowrap font-medium text-blue-700 hover:text-blue-600" do %>
            View Now <span aria-hidden="true">&rarr;</span></a>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end %>

<div class="mx-auto p-4 max-w-screen-xl sm:px-6 lg:p-8">
  <% if @group.shows.empty? %>
    <%= render partial: 'layouts/empty', locals: { content: "Your group does not have any shows!" } %>
  <% end %>

  <div class="space-y-12">
    <% if @airing.size > 0 %>
      <h2 class="text-3xl leading-9 font-extrabold tracking-tight sm:text-4xl">Airing</h2>

      <ul class="space-y-12 lg:grid lg:grid-cols-2 lg:items-start lg:gap-x-8 lg:gap-y-12 lg:space-y-0">
        <%= render partial: 'shows/show', collection: @airing, cached: ->(show) { [show, @group] } %>
      </ul>
    <% end %>

    <% if @active.size > 0 %>
      <h2 class="text-3xl leading-9 font-extrabold tracking-tight sm:text-4xl">Active</h2>

      <ul class="space-y-12 lg:grid lg:grid-cols-2 lg:items-start lg:gap-x-8 lg:gap-y-12 lg:space-y-0">
        <%= render partial: 'shows/show', collection: @active, cached: ->(show) { [show, @group] } %>
      </ul>
    <% end %>

    <% if @finished.size > 0 %>
      <h2 class="text-3xl leading-9 font-extrabold tracking-tight sm:text-4xl">Finished</h2>

      <ul class="space-y-12 lg:grid lg:grid-cols-2 lg:items-start lg:gap-x-8 lg:gap-y-12 lg:space-y-0">
        <%= render partial: 'shows/show', collection: @finished, cached: ->(show) { [show, @group] } %>
      </ul>
    <% end %>
  </div>
</div>

app/views/shows/show.html.erb
<% content_for :title, @show.name %>

<% content_for :page_actions do %>
  <%= render partial: "layouts/page_actions", locals: { page_actions: [
    { name: 'View Episodes', url: group_show_episodes_url(@group, @show) },
    { name: 'Edit Show', url: edit_group_show_url(@group, @show), highlight: true }
  ]}  %>
<% end %>

<div class="px-4 py-5 sm:p-6">
  <dl class="grid grid-cols-1 gap-x-4 gap-y-8 grid-flow-row-dense sm:grid-cols-2">
    <div class="sm:col-span-1">
      <div class="w-full sm:w-36 md:w-52 lg:w-64 m-auto">
        <div class="relative h-0 pb-2/3 sm:pt-2/3">
          <% if @show.poster.attached? %>
            <%= image_tag url_for(@show.poster), alt: "#{@show.name} Poster", class: "absolute inset-0 object-cover h-full w-full shadow-lg rounded-lg" %>
          <% else %>
            <div class="absolute inset-0 object-cover h-full w-full shadow-lg rounded-lg bg-gradient-to-r from-orange-400 via-red-500 to-pink-500"></div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="sm:col-span-1">
      <dt class="text-sm leading-5 font-medium text-gray-500">
        Name
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900">
        <%= @show.name %>
      </dd>
      <dt class="mt-4 text-sm leading-5 font-medium text-gray-500">
        Visibility
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900">
        <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium leading-5 <%= @show.visible ? "bg-green-100 text-green-800" : "bg-red-100 text-red-800" %>">
          <%= @show.visible ? "Public" : "Hidden" %>
        </span>
      </dd>
      <dt class="mt-4 text-sm leading-5 font-medium text-gray-500">
        Status
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900">
        <%= @show.status || "No Status" %>
      </dd>
      <dt class="mt-4 text-sm leading-5 font-medium text-gray-500">
        Season
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900">
        <%= @show.season %>
      </dd>
    </div>
  </dl>
  <dl class="mt-6">
    <div class="mt-8 sm:mt-0 sm:grid sm:grid-cols-3 sm:gap-4 sm:border-t sm:border-gray-200 sm:px-6 sm:py-5">
      <dt class="text-sm leading-5 font-medium text-gray-500">
        Terms

        <div class="mt-4">
          <span class="shadow-sm rounded-md">
            <%= link_to "Add Term", new_group_show_term_url(@group, @show), class: "inline-flex items-center px-4 py-2 border text-sm leading-5 font-medium rounded-md focus:outline-none transition duration-150 ease-in-out border-transparent text-white bg-indigo-600 hover:bg-indigo-500 focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700" %>
          </span>
        </div>
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
        <% if @show.terms.any? %>
          <ul class="border border-gray-200 rounded-md">
            <% @show.terms.each_with_index do |term, index| %>
              <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm leading-5 <%= "border-t border-gray-200 " if index > 0 %>"%>
                <div class="w-0 flex-1 flex items-center">
                  <span class="ml-2 flex-1 w-0 truncate">
                    <%= term.name %>
                  </span>
                </div>
                <div class="ml-4 flex-shrink-0">
                  <%= link_to "Delete", group_show_term_url(@group, @show, term), method: :delete, data: { confirm: "Do you wish to delete the term \"#{term.name}\"?" }, class: "font-medium text-red-600 hover:text-red-500 transition duration-150 ease-in-out" %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </dd>
    </div>

    <div class="mt-8 sm:mt-0 sm:grid sm:grid-cols-3 sm:gap-4 sm:border-t sm:border-gray-200 sm:px-6 sm:py-5">
      <dt class="text-sm leading-5 font-medium text-gray-500">
        Joint Groups
        <div class="mt-4">
          <span class="shadow-sm rounded-md">
            <%= link_to "Add Group", new_group_show_project_url(@group, @show), class: "inline-flex items-center px-4 py-2 border text-sm leading-5 font-medium rounded-md focus:outline-none transition duration-150 ease-in-out border-transparent text-white bg-indigo-600 hover:bg-indigo-500 focus:shadow-outline-indigo focus:border-indigo-700 active:bg-indigo-700" %>
          </span>
        </div>
      </dt>
      <dd class="mt-1 text-sm leading-5 text-gray-900 sm:mt-0 sm:col-span-2">
        <% if @show.projects.where.not(status: :declined).size > 1 %>
          <ul class="border border-gray-200 rounded-md">
            <% @show.projects.where.not(group: @group).where.not(status: :declined).each_with_index do |project, index| %>
              <li class="pl-3 pr-4 py-3 flex items-center justify-between text-sm leading-5 <%= "border-t border-gray-200" if index > 0 %>">
                <div class="w-0 flex-1 flex items-center">
                  <%= render partial: 'groups/icon', locals: { group: project.group, width: "w-5", height: "h-5" } %>
                  <span class="ml-2 flex-1 w-0 truncate">
                    <%= project.group.fullname %>
                  </span>
                  <% if project.pending? %>
                    <span class="inline-flex items-center px-3 py-0.5 rounded-full text-sm font-medium leading-5 <%= status_color_classes(project.status) %>">
                      <%= project.status.titleize %>
                    </span>
                  <% end %>
                </div>
                <div class="ml-4 flex-shrink-0">
                  <%= link_to "Remove", group_show_project_url(project.group, @show, project, status: :declined), method: :patch, data: { confirm: "Do you wish to remove #{project.group.name} from this project?" }, class: "font-medium text-red-600 hover:text-red-500 transition duration-150 ease-in-out" %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </dd>
    </div>
  </dl>
</div>